language: node_js
node_js:
  - lts/*

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: dist
  target_branch: master
  fqdn: tiim.ch
  on:
    branch: source
